# Generated by Django 5.2.17 on 2026-10-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
