# Generated by Django 5.2.17 on 2026-10-06 02:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_last_reminded_at'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='weekly', max_length=8)),
                ('next_run', models.DateField(help_text='Date the next invoice is created and sent')),
                ('days_until_due', models.PositiveIntegerField(default=7)),
                ('message', models.TextField(blank=True, help_text='Optional note shown to the client')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='billing.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clients.client')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='RecurringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.recurringinvoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service')),
            ],
        ),
    ]
